version: '3.8'

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1450"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_DB: federated_imputation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_db_password_2025}
    # Database port removed from external access for security
    # ports:
    #   - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d federated_imputation"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,web,192.168.101.147
      - DB_NAME=federated_imputation
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - H3AFRICA_API_URL=https://h3africa.org/api/v1/
      - H3AFRICA_API_KEY=demo_key
      - MICHIGAN_API_URL=https://imputationserver.sph.umich.edu/api/v2/
      - MICHIGAN_API_KEY=demo_key
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A federated_imputation worker --loglevel=info
    depends_on:
      web:
        condition: service_healthy
    environment:
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DEBUG=1
      - DB_NAME=federated_imputation
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - H3AFRICA_API_URL=https://h3africa.org/api/v1/
      - H3AFRICA_API_KEY=demo_key
      - MICHIGAN_API_URL=https://imputationserver.sph.umich.edu/api/v2/
      - MICHIGAN_API_KEY=demo_key
    volumes:
      - .:/app
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A federated_imputation beat --loglevel=info
    depends_on:
      web:
        condition: service_healthy
    environment:
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DEBUG=1
      - DB_NAME=federated_imputation
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://154.114.10.123:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: 