# Generated by Django 4.2.7 on 2025-08-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imputation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imputationservice',
            name='api_config',
            field=models.JSONField(blank=True, default=dict, help_text='Additional API-specific configuration'),
        ),
        migrations.AddField(
            model_name='imputationservice',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for authentication', max_length=255),
        ),
        migrations.AddField(
            model_name='imputationservice',
            name='api_type',
            field=models.CharField(choices=[('michigan', 'Michigan Imputation Server API'), ('ga4gh', 'GA4GH Service Info')], default='michigan', max_length=20),
        ),
    ]
