# Generated by Django 4.2.7 on 2025-08-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imputation', '0002_add_api_type_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imputationservice',
            name='api_type',
            field=models.CharField(choices=[('michigan', 'Michigan Imputation Server API'), ('ga4gh', 'GA4GH Service Info'), ('dnastack', 'DNASTACK Omics API')], default='michigan', max_length=20),
        ),
    ]
