# Generated by Django 4.2.7 on 2025-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imputation', '0003_add_dnastack_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imputationjob',
            name='user_token',
            field=models.CharField(blank=True, help_text="User's authentication token for the service", max_length=500),
        ),
    ]
