# Generated by Django 4.2.7 on 2025-08-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imputation', '0004_imputationjob_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='imputationservice',
            name='location',
            field=models.CharField(blank=True, help_text='Geographic location or institution hosting the service', max_length=200),
        ),
    ]
