# Generated by Django 4.2.7 on 2025-08-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imputation', '0005_add_location_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='imputationservice',
            name='continent',
            field=models.CharField(blank=True, help_text='Continent where the service is located', max_length=50),
        ),
    ]
